Repository DonateDonate/gather-here-Flutter, pull requests merged in 2024-10, with the labels that each got.

#31 feature: 검색 결과를 바텀 시트에 출력하도록 수정, 리스트 중 하나의 아이템을 탭 했을 시 해당 마커로 카메라 이동
  lib/screen/home/home_screen.dart
Labels: 기능

#32 [D-0] Refactor HomeScreen
  lib/common/components/default_layout.dart
  lib/common/router/router.dart
  lib/screen/debug/debug_screen.dart
  lib/screen/home/home_provider.dart
  lib/screen/home/home_screen.dart
Labels: 버그

#33 Feature/background
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  lib/common/background/initialize_service.dart
  lib/common/storage/storage.dart
  lib/main.dart
  lib/screen/home/home_provider.dart
  lib/screen/share/share_provider.dart
  lib/screen/share/share_screen.dart
  lib/screen/share/socket_manager.dart
  pubspec.yaml
Labels: 기능

#34 [D-0] 잡다한 문제 수정
  ios/Runner.xcodeproj/project.pbxproj
  lib/common/background/initialize_service.dart
  lib/common/components/default_date_dialog.dart
  lib/common/const/colors.dart
  lib/common/const/const.dart
  lib/common/location/location_manager.dart
  lib/common/model/response/search_response_model.g.dart
  lib/common/model/socket_request_model.dart
  lib/common/model/socket_response_model.dart
  lib/common/model/socket_response_model.g.dart
  lib/main.dart
  lib/screen/home/home_provider.dart
  lib/screen/home/home_screen.dart
  lib/screen/login/login_screen.dart
  lib/screen/share/Image_marker.dart
  lib/screen/share/share_provider.dart
  lib/screen/share/share_screen.dart
  lib/screen/share/socket_manager.dart
  pubspec.lock
  pubspec.yaml
Labels: 버그, 기능

#36 [D-0] 기타 작업 모음
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  asset/img/appIcon.png
  asset/img/medal.svg
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Assets.xcassets/AppIcon.appiconset/1024.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/114.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/120.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/180.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/29.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/40.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/57.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/58.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/60.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/80.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/87.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  ios/Runner/Info.plist
  lib/screen/share/share_screen.dart
  lib/screen/splash/splash_screen.dart
Labels: 기능

#39 fix: 이미지 캐싱 적용, 마커에 닉네임 추가, 이미지 용량 압축하여 서버에 전송
  lib/common/provider/member_info_provider.dart
  lib/common/utils/utils.dart
  lib/screen/home/custom_marker.dart
  lib/screen/home/home_screen.dart
  lib/screen/my_page/my_page_provider.dart
  lib/screen/my_page/my_page_screen.dart
  lib/screen/share/Image_marker.dart
  lib/screen/share/share_provider.dart
  lib/screen/share/share_screen.dart
  pubspec.yaml
Labels: 버그, 기능

#40 [D-0]: 개발자 화면 구현
  asset/img/flutter.png
  asset/img/github.png
  asset/img/spring.png
  asset/img/ubuntu.png
  lib/common/router/router.dart
  lib/screen/developer/developer_screen.dart
  lib/screen/home/home_screen.dart
  lib/screen/my_page/my_page_screen.dart
  lib/screen/share/share_screen.dart
Labels: 기능

#42 [D-0]: 기타 버그 픽스
  lib/common/location/location_manager.dart
  lib/common/model/socket_response_model.dart
  lib/common/provider/member_info_provider.dart
  lib/common/utils/utils.dart
  lib/main.dart
  lib/screen/design_system/design_system_button_screen.dart
  lib/screen/design_system/design_system_screen.dart
  lib/screen/developer/developer_screen.dart
  lib/screen/home/home_provider.dart
  lib/screen/home/home_screen.dart
  lib/screen/login/login_screen.dart
  lib/screen/my_page/my_page_provider.dart
  lib/screen/my_page/my_page_screen.dart
  lib/screen/share/image_marker.dart
  lib/screen/share/share_provider.dart
  lib/screen/share/share_screen.dart
  lib/screen/share/socket_manager.dart
  lib/screen/splash/splash_screen.dart
Labels: 버그, 기능
