Repository DonateDonate/gather-here-Flutter, pull requests merged in 2024-09, with the labels that each got.

#22 [D-0] 홈스크린에 여러 기능추가
  lib/common/location/location_manager.dart
  lib/screen/home/home_provider.dart
  lib/screen/home/home_screen.dart
Labels: 기능

#25 [D-0] 홈화면 버그 수정 (바텀시트 & 검색후 해당 위치로 이동 기능)
  ios/Runner.xcodeproj/project.pbxproj
  lib/screen/home/home_provider.dart
  lib/screen/home/home_screen.dart
Labels: 버그, 기능

#24 feature: 멤버 정보 가져오는 코드 분리, 마이 페이지에서 정보 수정하고 다시 홈 화면으로 나올 때 수정된 정보 반영,…
  lib/common/provider/member_info_provider.dart
  lib/screen/home/home_provider.dart
  lib/screen/home/home_screen.dart
  lib/screen/my_page/my_page_provider.dart
  lib/screen/my_page/my_page_screen.dart
Labels: 버그

#27 [D-0] 공유화면 맴버 리스트 바텀시트 + 타이머 + getRoom api 추가
  lib/common/repository/room_repository.dart
  lib/common/repository/room_repository.g.dart
  lib/common/utils/utils.dart
  lib/screen/home/home_provider.dart
  lib/screen/home/home_screen.dart
  lib/screen/share/share_provider.dart
  lib/screen/share/share_screen.dart
Labels: 기능

#28 feature: DatePicker, TimePicker, 구글 맵 ui 변경, Dialog 수정
  lib/common/components/default_date_dialog.dart
  lib/screen/home/home_provider.dart
  lib/screen/home/home_screen.dart
  lib/screen/my_page/my_page_provider.dart
  lib/screen/my_page/my_page_screen.dart
  pubspec.yaml
Labels: 버그, 기능

#29 Feature/custom marker
  lib/common/dio/dio.dart
  lib/common/location/location_manager.dart
  lib/common/model/response/search_response_model.dart
  lib/common/provider/member_info_provider.dart
  lib/screen/home/custom_marker.dart
  lib/screen/home/home_provider.dart
  lib/screen/home/home_screen.dart
  lib/screen/my_page/my_page_screen.dart
  lib/screen/sign_up/sign_up_screen.dart
Labels: 버그, 기능
